package UI;

/**
 *
 * @author Liu Ching Richard
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ingresarFactura = new javax.swing.JButton();
        buscarFactura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liu Ching Richard Proyecto 2");
        setResizable(false);

        transportes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        transportes.setText("Gestionar Transportes");
        transportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gestionar Alquileres:");

        ingresarFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ingresarFactura.setText("Ingresar Factura");
        ingresarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarFacturaActionPerformed(evt);
            }
        });

        buscarFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscarFactura.setText("Buscar Factura");
        buscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFacturaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Menú Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(transportes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ingresarFactura)
                        .addGap(56, 56, 56)
                        .addComponent(buscarFactura)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(transportes)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarFactura)
                    .addComponent(buscarFactura))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportesActionPerformed
        // Se crea una instancia del JFrame de Transportes
        GestionTransporte gestionTransporteFrame = new GestionTransporte();

        // Hacer visible el JFrame de Transportes
        gestionTransporteFrame.setVisible(true);

        // Ocultar el JFrame de MenuPrincipal
        this.setVisible(false);
    }//GEN-LAST:event_transportesActionPerformed

    private void ingresarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarFacturaActionPerformed
        // Se crea una instancia del JFrame de Insertar Factura
        IngresarFactura ingresarFacturaFrame = new IngresarFactura();

        // Hacer visible el JFrame de Ingreso de Factura
        ingresarFacturaFrame.setVisible(true);

        // Ocultar el JFrame de MenuPrincipal
        this.setVisible(false);
    }//GEN-LAST:event_ingresarFacturaActionPerformed

    private void buscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFacturaActionPerformed
        // Se crea una instancia del JFrame de Buscar Factura
        BuscarFactura buscarFacturaFrame = new BuscarFactura();

        // Hacer visible el JFrame de Buscar Factura
        buscarFacturaFrame.setVisible(true);

        // Ocultar el JFrame de MenuPrincipal
        this.setVisible(false);
    }//GEN-LAST:event_buscarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarFactura;
    private javax.swing.JButton ingresarFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton transportes;
    // End of variables declaration//GEN-END:variables
}
